//
// Copyright (c) 2020 - Yupiik SAS - https://www.yupiik.com
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

= Yupiik Tools Maven Plugin
:toc:

image::https://github.com/yupiik/tools-maven-plugin/workflows/Java%20CI%20with%20Maven/badge.svg[Java CI with Maven]

A set of goals at Yupiik colors.

Plugin definition:

[source,xml]
----
<plugin>
  <groupId>io.yupiik.maven</groupId>
  <artifactId>yupiik-tools-maven-plugin</artifactId>
  <version>${yupiik-tools.version}</version>
</plugin>
----

== Goals

=== PDF

Render an asciidoctor file in PDF.

Simplest setup is to define the plugin and create a file `src/main/pdf/index.adoc`, then simply render it with:

[source,sh]
----
 mvn yupiik-tools:pdf
----

==== Configuration

[options="header",cols="1,m,m,m,1"]
|====
|Name|Type|Default|Property|Description
|attributes|Map|-|-|Custom attributes.
|customCss|File|-|yupiik.slides.customCss|Custom css if needed, overrides default one for revealjs (as intended by the backend) and append it to yupiik one for bespoke.
|mode|Mode|DEFAULT|yupiik.slides.mode|Which execution mode to use, WATCH and SERVE are for dev purposes.
|port|int|4200|yupiik.slides.serve.port|For SERVE mode, which port to bind.
|source|File|${project.basedir}/src/main/pdf/index.adoc|yupiik.slides.source|Slide deck source file.
|targetDirectory|File|${project.build.directory}/yupiik/pdf|yupiik.slides.target|Where to render the slide deck.
|workDir|File|${project.build.directory}/yupiik-workdir|yupiik.workDir|Where to extract files needed for the rendering.
|====

==== PDF and formula

Stem/Math formulas Asciidoctor integration is done through _mathematical_ gem which uses native bindings not supported by JRuby.
Therefore you can't use it with PDF.
To workaround this issue, PDF plugin provides `jlatexmath` (open block macro, i.e. delimited with `--`) and `jmath` (inline macro) allowing you to use inline LaTeX formulas.

To activate it you must add jlatexmath dependency:

[source,xml]
----
<plugin>
  <groupId>io.yupiik.maven</groupId>
  <artifactId>yupiik-tools-maven-plugin</artifactId>
  <configuration>
    <!-- ... -->
  </configuration>
  <dependencies>
    <dependency>
      <groupId>org.scilab.forge</groupId>
      <artifactId>jlatexmath</artifactId>
      <version>1.0.7</version>
    </dependency>
  </dependencies>
</plugin>
----

Example:

[source,asciidoc]
----

[jlatexmath]
--
x = a + b
--

This formula (jmath:_[a + b]) is cool.
----

=== Slides

Render an asciidoctor reveal.js slide deck in HTML.

Simplest setup is to define the plugin and create a file `src/main/slides/index.adoc`, then simply render it with:

[source,sh]
----
mvn yupiik-tools:slides
----

You can also pass in HTTP mode with:

[source,sh]
----
mvn yupiik-tools:serve-slides
----

TIP: to convert slides to PDF, you can use decktape. Launch the slides HTTP server and then run `docker run --rm -t --net=host -v $PWD:/slides astefanutti/decktape http://localhost:4200 slides.pdf`.

==== Configuration

[options="header",cols="1,m,m,m,1"]
|====
|Name|Type|Default|Property|Description
|attributes|Map|-|-|Custom attributes. By default _partials and images folders are set to partialsdir and imagesdir attributes.
|sourceDirectory|File|${project.basedir}/src/main/pdf|yupiik.pdf.source|Source directory or file to render, if a directory all files with extension .adoc will be selected.
|targetDirectory|File|${project.build.directory}/yupiik/pdf|yupiik.pdf.target|Where to render the asciidoc files to.
|themeDir|File|-|yupiik.pdf.themeDir|Theme directory (name of the theme is yupiik), let it null to inherit from the default theme.
|workDir|File|${project.build.directory}/yupiik-workdir|yupiik.workDir|Where to extract files needed for the rendering.
|slider|Slider|BESPOKE|yupiik.slides.slidere|Which renderer to use for slides, reveal.js or bespoke.js.
|synchronizationFolders|List of source,target|-|-|List of synchronization folder for the output, source will be taken (file) and copied relatively to target directory, appending target value before the relative path of the file.
|====

=== Audit

Audit mojo uses the fact the plugins are "Maven aware" to generate an audit report inheriting from PDF mojo.
It uses the same configuration but works on a reactor.

TIP: it is recommended to set `source` relative to multiple module dir and not project basedir since this one can be random.

Here is a sample execution from the CLI:

[source,sh]
----
$ mvn io.yupiik.maven:yupiik-tools-maven-plugin:${plugin.version}:audit \
    -Dyupiik.pdf.source=$PWD/report.adoc \
    -Dyupiik.pdf.target=/tmp/report
[...]
mvn io.yupiik.maven:yupiik-tools-maven-plugin:1.0.0-SNAPSHOT:audit -Dyupiik.pdf.source=report.adoc -Dyupiik.pdf.target=/tmp/report.pdf
[INFO] --- yupiik-tools-maven-plugin:1.0.0-SNAPSHOT:audit (default-cli) @ my-module ---
[INFO] Generating audit report
[INFO] Rendered 'report.adoc'
----

A more complete example to skip a module, skip some plugins and ensure dependencies are available can be:

[source,sh]
----
 mvn \
    compile -Dcompiler.skip=true  \ <1>
    io.yupiik.maven:yupiik-tools-maven-plugin:${plugin.version}:audit \ <2>
    -Dyupiik.pdf.source=$PWD/report.adoc -Dyupiik.pdf.target=/tmp/report \
    -Dlicense.skip=true -Dfront.build.skip=true \ <3>
    -pl -documentation <4>
----

<1> go through compile phase (skipping it) to ensure compile dependencies are resolved,
<2> our audit plugin *after* the resolution plugins,
<3> skip license and front plugins (depends your plugins),
<4> skip documentation module.

Report will be in `/tmp/report/report.pdf`.

NOTE: report does not have to be in the project ;).

Here is a sample report:

[listing]
....
= Report

== Dependencies

[maven_dependencies,scope=compile_only,aggregated=true] <1>
--
--
....

<1> the `aggregated=true` enables to generate a single report for all the reactor at once.


=== Minisite

Minisite enables to render a static website with a generic Yupiik template.
It comes with its companion serve goal to have a live preview.

[source,sh]
----
 mvn yupiik-tools:minisite
 mvn yupiik-tools:serve-minisite
----

==== Configuration

[options="header",cols="1,m,m,m,1"]
|====
|Name|Type|Default|Property|Description
|attributes|Map|-|-|Custom attributes.
|source|File|${project.basedir}/src/main/minisite|yupiik.minisite.source|Source directory or file to render.
|target|File|${project.build.directory}/${project.build.finalName}|yupiik.minisite.target|Where to render the minisite.
|title|String|Yupiik|yupiik.minisite.title|Default title if page has no title.
|description|String|Yupiik Minisite|yupiik.minisite.description|Default description if page has no title.
|siteBase|String|`http://localhost:4200`|yupiik.minisite.siteBase|Base of the site.
|searchIndexName|String|search.json|yupiik.minisite.generateSearchIndex|Should search.json be generated and if not `none` its name.
|generateIndex|boolean|true|yupiik.minisite.generateIndex|Should index be generated from the pages.
|generateSiteMap|boolean|true|yupiik.minisite.generateSiteMap|Should sitemap be generated.
|templatePrefixes|List<String>|default|-|List of html templates to prepend to the content.
|templateAddLeftMenu|boolean|true|yupiik.minisite.addLeftMenu|Should a left menu inheriting from index logic be generated.
|templateSuffixes|List<String>|default|-|List of html templates to append to the content.
|useDefaultAssets|boolean|true|yupiik.minisite.useDefaultAssets|Should default css/js be extracted and added to the website.
|customHead|String|-|yupiik.minisite.customHead|String injected at the end of head tag of html pages.
|customScripts|String|-|yupiik.minisite.customScripts|String injected at the end of script tags of html pages.
|====

The configuration also supports a `ftp` entry if you want to upload to a FTP server the generated website:

[options="header",cols="1,m,m,m,1"]
|====
|Name|Type|Description
|username|String|Username if serverId is not set.
|password|String|Password if serverId is not set.
|serverId|String|ServerID to use to get username/password from settings.xml.
|url|String|FTP url (`ftp://host:port/dir`).
|====

===== Example

[source,xml]
----
<plugin>
  <groupId>io.yupiik.maven</groupId>
  <artifactId>yupiik-tools-maven-plugin</artifactId>
  <executions>
    <execution>
      <id>build-and-deploy-doc</id>
      <phase>package</phase>
      <goals>
        <goal>minisite</goal>
      </goals>
      <configuration>
        <siteBase>http://mini.yupiik.net</siteBase>
        <ftp>
          <serverId>http://mini.yupiik.net</serverId> <!-- default is siteBase -->
          <url>ftp://ftpupload.net/htdocs</url>
        </ftp>
      </configuration>
    </execution>
  </executions>
</plugin>
----

===== Index generation

To include a page in the index it must contain `minisite-index` attribute.
Its value is the order of the entry in the index tiles.

TIP: ensure to not use `1`, `2`, `3`, ... but rather `100`, `200`, ... to easily insert an item later.

* `minisite-index-title` attribute enables to override link text.
* `minisite-index-icon` attribute enables to override font awesome icon (without `fa-` prefix).
* `minisite-index-description` attribute enables to override the text in the index tile for the page entry.

== Maven Asciidoctor Macro

The project adds asciidoc macros to get back some maven build information.
Note that it must be executed in the right lifecycle phase if using some project metadata (plugin does not require any resolution to be usable standalone).

=== maven_dependencies

Enables to list the project dependencies.

==== Usage

[listing]
....
[maven_dependencies,scope=compile]
--
--
....

Scope can be:

- compile
- runtime
- compile+runtime
- runtime+system
- test
- provided_only
- compile_only
- test_only
- system_only
- runtime_only

The optional attribute `groupId` is also supported and take a list (comma separated) of groupId to include.
