= yupiik-tools:slides

Custom attributes.

== Coordinates

[source,xml]
----
<plugin>
  <groupId>io.yupiik.maven</groupId>
  <artifactId>yupiik-tools-maven-plugin</artifactId>
  <version>1.0.27-SNAPSHOT</version>
</plugin>
----

To call this goal from the command line execute: `mvn yupiik-tools:slides`.

To bind this goal in the build you can use:

[source,xml]
----
<plugin>
  <groupId>io.yupiik.maven</groupId>
  <artifactId>yupiik-tools-maven-plugin</artifactId>
  <version>1.0.27-SNAPSHOT</version>
  <executions>
    <execution>
      <id>my-execution</id>
      <goals>
        <goal>slides</goal>
      </goals>
      <configuration>
        <!-- execution specific configuration come there -->
      </configuration>
    </execution>
  </executions>
</plugin>
----

You can execute this goal particularly with `mvn yupiik-tools:slides@my-execution` command.

== Configuration

attributes (`Map`)::
Custom attributes.

customCss (`java.io.File`)::
Custom css if needed, overrides default one. Property: `${yupiik.slides.customCss}`.

customScripts (`String[]`)::
Custom js if needed. Property: `${yupiik.slides.customScripts}`.

mode (`io.yupiik.tools.slides.SlidesConfiguration$Mode`)::
Which execution mode to use, WATCH and SERVE are for dev purposes. Default value: `DEFAULT`. Property: `${yupiik.slides.mode}`.

port (`int`)::
For SERVE mode, which port to bind. Default value: `4200`. Property: `${yupiik.slides.serve.port}`.

requires (`List`)::
Warning: this must be a shared settings by all executions.
Override defaults require - completely.

slider (`io.yupiik.tools.slides.SlidesConfiguration$SliderType`)::
Which renderer (slide) to use. Default value: `BESPOKE_ENRICHED`. Property: `${yupiik.slides.slider}`.

source (`java.io.File`)::
Slide deck source file. Default value: `${project.basedir}/src/main/slides/index.adoc`. Property: `${yupiik.slides.source}`.

synchronizationFolders (`List`)::
Synchronize folders.

targetDirectory (`java.io.File`)::
Where to render the slide deck. Default value: `${project.build.directory}/yupiik/slides`. Property: `${yupiik.slides.target}`.

templateDirs (`java.io.File`)::
Template directory if set. Property: `${yupiik.slides.templateDirs}`.

watchDelay (`int`)::
How long to wait to check if render must be re-done in watch mode (in ms). Default value: `150`. Property: `${yupiik.slides.watchDelay}`.

workDir (`java.io.File`)::
Where to extract files needed for the rendering. Default value: `${project.build.directory}/yupiik-workdir`. Property: `${yupiik.workDir}`.

