/*
 * Copyright (c) 2020 - present - Yupiik SAS - https://www.yupiik.com
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package io.yupiik.asciidoc.renderer.html;

import java.util.Map;
import java.util.function.Function;

import static java.util.Map.entry;

/**
 * Simple function enabling to escape a string value as a HTML(4) one.
 */
public class HtmlEscaping implements Function<String, String> {
    public static final HtmlEscaping INSTANCE = new HtmlEscaping();

    // taken from commons-value
    private final Map<Character, String> escaped = Map.ofEntries(
            entry('"', "&quot;"),
            entry('&', "&amp;"),
            entry('<', "&lt;"),
            entry('>', "&gt;"),
            entry('\u00A0', "&nbsp;"),
            entry('\u00A1', "&iexcl;"),
            entry('\u00A2', "&cent;"),
            entry('\u00A3', "&pound;"),
            entry('\u00A4', "&curren;"),
            entry('\u00A5', "&yen;"),
            entry('\u00A6', "&brvbar;"),
            entry('\u00A7', "&sect;"),
            entry('\u00A8', "&uml;"),
            entry('\u00A9', "&copy;"),
            entry('\u00AA', "&ordf;"),
            entry('\u00AB', "&laquo;"),
            entry('\u00AC', "&not;"),
            entry('\u00AD', "&shy;"),
            entry('\u00AE', "&reg;"),
            entry('\u00AF', "&macr;"),
            entry('\u00B0', "&deg;"),
            entry('\u00B1', "&plusmn;"),
            entry('\u00B2', "&sup2;"),
            entry('\u00B3', "&sup3;"),
            entry('\u00B4', "&acute;"),
            entry('\u00B5', "&micro;"),
            entry('\u00B6', "&para;"),
            entry('\u00B7', "&middot;"),
            entry('\u00B8', "&cedil;"),
            entry('\u00B9', "&sup1;"),
            entry('\u00BA', "&ordm;"),
            entry('\u00BB', "&raquo;"),
            entry('\u00BC', "&frac14;"),
            entry('\u00BD', "&frac12;"),
            entry('\u00BE', "&frac34;"),
            entry('\u00BF', "&iquest;"),
            entry('\u00C0', "&Agrave;"),
            entry('\u00C1', "&Aacute;"),
            entry('\u00C2', "&Acirc;"),
            entry('\u00C3', "&Atilde;"),
            entry('\u00C4', "&Auml;"),
            entry('\u00C5', "&Aring;"),
            entry('\u00C6', "&AElig;"),
            entry('\u00C7', "&Ccedil;"),
            entry('\u00C8', "&Egrave;"),
            entry('\u00C9', "&Eacute;"),
            entry('\u00CA', "&Ecirc;"),
            entry('\u00CB', "&Euml;"),
            entry('\u00CC', "&Igrave;"),
            entry('\u00CD', "&Iacute;"),
            entry('\u00CE', "&Icirc;"),
            entry('\u00CF', "&Iuml;"),
            entry('\u00D0', "&ETH;"),
            entry('\u00D1', "&Ntilde;"),
            entry('\u00D2', "&Ograve;"),
            entry('\u00D3', "&Oacute;"),
            entry('\u00D4', "&Ocirc;"),
            entry('\u00D5', "&Otilde;"),
            entry('\u00D6', "&Ouml;"),
            entry('\u00D7', "&times;"),
            entry('\u00D8', "&Oslash;"),
            entry('\u00D9', "&Ugrave;"),
            entry('\u00DA', "&Uacute;"),
            entry('\u00DB', "&Ucirc;"),
            entry('\u00DC', "&Uuml;"),
            entry('\u00DD', "&Yacute;"),
            entry('\u00DE', "&THORN;"),
            entry('\u00DF', "&szlig;"),
            entry('\u00E0', "&agrave;"),
            entry('\u00E1', "&aacute;"),
            entry('\u00E2', "&acirc;"),
            entry('\u00E3', "&atilde;"),
            entry('\u00E4', "&auml;"),
            entry('\u00E5', "&aring;"),
            entry('\u00E6', "&aelig;"),
            entry('\u00E7', "&ccedil;"),
            entry('\u00E8', "&egrave;"),
            entry('\u00E9', "&eacute;"),
            entry('\u00EA', "&ecirc;"),
            entry('\u00EB', "&euml;"),
            entry('\u00EC', "&igrave;"),
            entry('\u00ED', "&iacute;"),
            entry('\u00EE', "&icirc;"),
            entry('\u00EF', "&iuml;"),
            entry('\u00F0', "&eth;"),
            entry('\u00F1', "&ntilde;"),
            entry('\u00F2', "&ograve;"),
            entry('\u00F3', "&oacute;"),
            entry('\u00F4', "&ocirc;"),
            entry('\u00F5', "&otilde;"),
            entry('\u00F6', "&ouml;"),
            entry('\u00F7', "&divide;"),
            entry('\u00F8', "&oslash;"),
            entry('\u00F9', "&ugrave;"),
            entry('\u00FA', "&uacute;"),
            entry('\u00FB', "&ucirc;"),
            entry('\u00FC', "&uuml;"),
            entry('\u00FD', "&yacute;"),
            entry('\u00FE', "&thorn;"),
            entry('\u00FF', "&yuml;"),
            entry('\u0192', "&fnof;"),
            entry('\u0391', "&Alpha;"),
            entry('\u0392', "&Beta;"),
            entry('\u0393', "&Gamma;"),
            entry('\u0394', "&Delta;"),
            entry('\u0395', "&Epsilon;"),
            entry('\u0396', "&Zeta;"),
            entry('\u0397', "&Eta;"),
            entry('\u0398', "&Theta;"),
            entry('\u0399', "&Iota;"),
            entry('\u039A', "&Kappa;"),
            entry('\u039B', "&Lambda;"),
            entry('\u039C', "&Mu;"),
            entry('\u039D', "&Nu;"),
            entry('\u039E', "&Xi;"),
            entry('\u039F', "&Omicron;"),
            entry('\u03A0', "&Pi;"),
            entry('\u03A1', "&Rho;"),
            entry('\u03A3', "&Sigma;"),
            entry('\u03A4', "&Tau;"),
            entry('\u03A5', "&Upsilon;"),
            entry('\u03A6', "&Phi;"),
            entry('\u03A7', "&Chi;"),
            entry('\u03A8', "&Psi;"),
            entry('\u03A9', "&Omega;"),
            entry('\u03B1', "&alpha;"),
            entry('\u03B2', "&beta;"),
            entry('\u03B3', "&gamma;"),
            entry('\u03B4', "&delta;"),
            entry('\u03B5', "&epsilon;"),
            entry('\u03B6', "&zeta;"),
            entry('\u03B7', "&eta;"),
            entry('\u03B8', "&theta;"),
            entry('\u03B9', "&iota;"),
            entry('\u03BA', "&kappa;"),
            entry('\u03BB', "&lambda;"),
            entry('\u03BC', "&mu;"),
            entry('\u03BD', "&nu;"),
            entry('\u03BE', "&xi;"),
            entry('\u03BF', "&omicron;"),
            entry('\u03C0', "&pi;"),
            entry('\u03C1', "&rho;"),
            entry('\u03C2', "&sigmaf;"),
            entry('\u03C3', "&sigma;"),
            entry('\u03C4', "&tau;"),
            entry('\u03C5', "&upsilon;"),
            entry('\u03C6', "&phi;"),
            entry('\u03C7', "&chi;"),
            entry('\u03C8', "&psi;"),
            entry('\u03C9', "&omega;"),
            entry('\u03D1', "&thetasym;"),
            entry('\u03D2', "&upsih;"),
            entry('\u03D6', "&piv;"),
            entry('\u2022', "&bull;"),
            entry('\u2026', "&hellip;"),
            entry('\u2032', "&prime;"),
            entry('\u2033', "&Prime;"),
            entry('\u203E', "&oline;"),
            entry('\u2044', "&frasl;"),
            entry('\u2118', "&weierp;"),
            entry('\u2111', "&image;"),
            entry('\u211C', "&real;"),
            entry('\u2122', "&trade;"),
            entry('\u2135', "&alefsym;"),
            entry('\u2190', "&larr;"),
            entry('\u2191', "&uarr;"),
            entry('\u2192', "&rarr;"),
            entry('\u2193', "&darr;"),
            entry('\u2194', "&harr;"),
            entry('\u21B5', "&crarr;"),
            entry('\u21D0', "&lArr;"),
            entry('\u21D1', "&uArr;"),
            entry('\u21D2', "&rArr;"),
            entry('\u21D3', "&dArr;"),
            entry('\u21D4', "&hArr;"),
            entry('\u2200', "&forall;"),
            entry('\u2202', "&part;"),
            entry('\u2203', "&exist;"),
            entry('\u2205', "&empty;"),
            entry('\u2207', "&nabla;"),
            entry('\u2208', "&isin;"),
            entry('\u2209', "&notin;"),
            entry('\u220B', "&ni;"),
            entry('\u220F', "&prod;"),
            entry('\u2211', "&sum;"),
            entry('\u2212', "&minus;"),
            entry('\u2217', "&lowast;"),
            entry('\u221A', "&radic;"),
            entry('\u221D', "&prop;"),
            entry('\u221E', "&infin;"),
            entry('\u2220', "&ang;"),
            entry('\u2227', "&and;"),
            entry('\u2228', "&or;"),
            entry('\u2229', "&cap;"),
            entry('\u222A', "&cup;"),
            entry('\u222B', "&int;"),
            entry('\u2234', "&there4;"),
            entry('\u223C', "&sim;"),
            entry('\u2245', "&cong;"),
            entry('\u2248', "&asymp;"),
            entry('\u2260', "&ne;"),
            entry('\u2261', "&equiv;"),
            entry('\u2264', "&le;"),
            entry('\u2265', "&ge;"),
            entry('\u2282', "&sub;"),
            entry('\u2283', "&sup;"),
            entry('\u2284', "&nsub;"),
            entry('\u2286', "&sube;"),
            entry('\u2287', "&supe;"),
            entry('\u2295', "&oplus;"),
            entry('\u2297', "&otimes;"),
            entry('\u22A5', "&perp;"),
            entry('\u22C5', "&sdot;"),
            entry('\u2308', "&lceil;"),
            entry('\u2309', "&rceil;"),
            entry('\u230A', "&lfloor;"),
            entry('\u230B', "&rfloor;"),
            entry('\u2329', "&lang;"),
            entry('\u232A', "&rang;"),
            entry('\u25CA', "&loz;"),
            entry('\u2660', "&spades;"),
            entry('\u2663', "&clubs;"),
            entry('\u2665', "&hearts;"),
            entry('\u2666', "&diams;"),
            entry('\u0152', "&OElig;"),
            entry('\u0153', "&oelig;"),
            entry('\u0160', "&Scaron;"),
            entry('\u0161', "&scaron;"),
            entry('\u0178', "&Yuml;"),
            entry('\u02C6', "&circ;"),
            entry('\u02DC', "&tilde;"),
            entry('\u2002', "&ensp;"),
            entry('\u2003', "&emsp;"),
            entry('\u2009', "&thinsp;"),
            entry('\u200C', "&zwnj;"),
            entry('\u200D', "&zwj;"),
            entry('\u200E', "&lrm;"),
            entry('\u200F', "&rlm;"),
            entry('\u2013', "&ndash;"),
            entry('\u2014', "&mdash;"),
            entry('\u2018', "&lsquo;"),
            entry('\u2019', "&rsquo;"),
            entry('\u201A', "&sbquo;"),
            entry('\u201C', "&ldquo;"),
            entry('\u201D', "&rdquo;"),
            entry('\u201E', "&bdquo;"),
            entry('\u2020', "&dagger;"),
            entry('\u2021', "&Dagger;"),
            entry('\u2030', "&permil;"),
            entry('\u2039', "&lsaquo;"),
            entry('\u203A', "&rsaquo;"),
            entry('\u20AC', "&euro;"));

    @Override
    public String apply(final String value) {
        StringBuilder result = null;
        for (int i = 0; i < value.length(); i++) {
            final var c = value.charAt(i);
            final var replacement = escaped.get(c);
            if (replacement != null) {
                if (result == null) {
                    result = new StringBuilder(value.substring(0, i));
                }
                result.append(replacement);
            } else if (result != null) {
                result.append(c);
            }
        }
        return result == null ? value : result.toString();
    }
}
